name: Feature request
description: Ajukan fitur baru
labels: [enhancement]
body:
- type: textarea
id: problem
attributes:
label: Masalah
description: Apa masalah yang ingin diselesaikan?
validations:
required: true
- type: textarea
id: solution
attributes:
label: Solusi yang diinginkan